import { GetStaticProps } from 'next'
import Head from 'next/head'
import Homepage from '../common/components/Homepage'
import DataList from '../common/components/DataList'
import { getData, APIData } from '../modules/dataService'
import Default from '../common/components/Layouts/Default'

export const getStaticProps: GetStaticProps = async () => {
    try {
        const data: APIData = await getData()
        console.log(`here's your data kind sire:`, data)

        return {
            props: {
                data,
            },
        }
    } catch (error) {
        return {
            notFound: true, // go to 404 page
        }
    }
}

export interface Data {
    data: Data
}
const Home = ({ data }: Data) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Homepage />
            <DataList data={data} />
        </div>
    )
}

Home.PageLayout = Default

export default Home
