import { GetStaticProps } from 'next'
import Head from 'next/head'
import Homepage from '../common/components/Homepage'
import DataList from '../common/components/DataList'
import {
    getData,
    APIData,
    DataObject,
    Field,
    Item,
} from '../modules/dataService'
import Default from '../common/components/Layouts/Default'
import { getPosition } from '../common/utils'

const getEnrichedData = (data: DataObject) => {
    const result = data.data.map((item: Field) => {
        return {
            ...item,
            items: item.items.map((it: Item) => ({
                ...it,
                position: getPosition(it),
            })),
        }
    })
    return { ...data, data: result }
}

export const getStaticProps: GetStaticProps = async () => {
    try {
        const dataList: APIData = await getData()

        const enrichedDataList = {
            ...dataList,
            data: getEnrichedData(dataList.data),
        }

        return {
            props: {
                dataList: enrichedDataList,
            },
        }
    } catch (error) {
        return {
            notFound: true, // go to 404 page
        }
    }
}

export interface Data {
    dataList: APIData
}
const Home = ({ dataList }: Data) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Homepage />

            <DataList dataList={dataList} />
        </div>
    )
}

Home.PageLayout = Default

export default Home
